{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-platetools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/platetools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/platetools/platetools_{{ version }}.tar.gz
  sha256: ab20dc75b72392d8e305abbd86a9698891a73dc7e24b361abe627ce4cd8091f8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2 >=2.2.0
  run:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2 >=2.2.0

test:
  commands:
    - $R -e "library('platetools')"           # [not win]
    - "\"%R%\" -e \"library('platetools')\""  # [win]

about:
  home: https://github.com/swarchal/platetools
  license: MIT
  summary: Collection of functions for working with multi-well microtitre plates, mainly 96, 384 and 1536 well plates.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: platetools
# Title: Tools and Plots for Multi-Well Plates
# Version: 0.1.2
# Authors@R: person("Scott", "Warchal", email = "scott.warchal@gmail.com", role = c("aut", "cre"))
# Description: Collection of functions for working with multi-well microtitre plates, mainly 96, 384 and 1536 well plates.
# Depends: R (>= 3.1.0)
# License: MIT + file LICENSE
# URL: https://github.com/swarchal/platetools
# BugReports: https://github.com/swarchal/platetools/issues
# Encoding: UTF-8
# LazyData: true
# Imports: RColorBrewer, ggplot2 (>= 2.2.0)
# Suggests: testthat, viridis
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2019-04-23 19:05:24 UTC; scott
# Author: Scott Warchal [aut, cre]
# Maintainer: Scott Warchal <scott.warchal@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-04-24 07:20:03 UTC
