travis:
  secure:
    BINSTAR_TOKEN: WxOHjn3fHzJXBp9L/iuDjCDkH3yg5kyq/gOFGedlrwTLIsxOS4phB3wE3EMP87ZRjN0xpP3NVWs3nDHnqzyecDRZ4wLhKSNRIQdLNM3YH9NWkzoEqOopD8FxEbQ7wY0DBNHCVKoDNH628Q/DyszZuKD2nG9aOrrsQ+16ZpiS6rxlPiZ3fdZm4MMeft5Hncfx5XXx8jyqsdSQ1nSlLWgZ1b5D/EvaSyuK+qZEEvzLyfN6yQhSxgnbsB54kPg/wUwTp02USMzh5Pv33xAQah7A5HUzh2MJeNTr+jPh3NxhUSusFSNKQlRj+J2YHSrej4sMfzACD0rbbAk6a11j0Jr47pZ6DMGz45kGCnAnX6qKuZ58n61XjHX5Tl71BSRujJjJa0wiQqf7d6NeAjUbYmu4FzUdxaZB88+avcqPu8nkpl2cxPb7WIas2SUXmA1uHq0FFx2MzasIvz+85idQ0I0w/1hPaJNvH2bhwPBBXaSt3V5bw6WFR5yRv7EcNLxO0XplSTUX/+9k4pVmmkEJXpgDeHlnm17nfd9YwuiZfi4s4qeAP6ryIsynG8ZlWCd7GyN07JjLQTo+kRjvkphIl7VKh92HF5xpvFhALPNnzU0JA2lyI+beTy5PmXvz9emVNhQGnvHK5BaaysrQYQIYWHlHDCKpylSz7SbmNwOF9/tV3Eo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
